name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and collect code coverage
      run: |
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    - name: Publish code coverage results
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
